version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - pfichtner
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - pfichtner
- package-ecosystem: maven
  directory: "/demo/java/sketchtest"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - pfichtner
